// Copyright Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1 "maistra.io/api/core/v1"
)

// FakeServiceMeshControlPlanes implements ServiceMeshControlPlaneInterface
type FakeServiceMeshControlPlanes struct {
	Fake *FakeCoreV1
	ns   string
}

var servicemeshcontrolplanesResource = v1.SchemeGroupVersion.WithResource("servicemeshcontrolplanes")

var servicemeshcontrolplanesKind = v1.SchemeGroupVersion.WithKind("ServiceMeshControlPlane")

// Get takes name of the serviceMeshControlPlane, and returns the corresponding serviceMeshControlPlane object, and an error if there is any.
func (c *FakeServiceMeshControlPlanes) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ServiceMeshControlPlane, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(servicemeshcontrolplanesResource, c.ns, name), &v1.ServiceMeshControlPlane{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ServiceMeshControlPlane), err
}

// List takes label and field selectors, and returns the list of ServiceMeshControlPlanes that match those selectors.
func (c *FakeServiceMeshControlPlanes) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ServiceMeshControlPlaneList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(servicemeshcontrolplanesResource, servicemeshcontrolplanesKind, c.ns, opts), &v1.ServiceMeshControlPlaneList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ServiceMeshControlPlaneList{ListMeta: obj.(*v1.ServiceMeshControlPlaneList).ListMeta}
	for _, item := range obj.(*v1.ServiceMeshControlPlaneList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested serviceMeshControlPlanes.
func (c *FakeServiceMeshControlPlanes) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(servicemeshcontrolplanesResource, c.ns, opts))

}

// Create takes the representation of a serviceMeshControlPlane and creates it.  Returns the server's representation of the serviceMeshControlPlane, and an error, if there is any.
func (c *FakeServiceMeshControlPlanes) Create(ctx context.Context, serviceMeshControlPlane *v1.ServiceMeshControlPlane, opts metav1.CreateOptions) (result *v1.ServiceMeshControlPlane, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(servicemeshcontrolplanesResource, c.ns, serviceMeshControlPlane), &v1.ServiceMeshControlPlane{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ServiceMeshControlPlane), err
}

// Update takes the representation of a serviceMeshControlPlane and updates it. Returns the server's representation of the serviceMeshControlPlane, and an error, if there is any.
func (c *FakeServiceMeshControlPlanes) Update(ctx context.Context, serviceMeshControlPlane *v1.ServiceMeshControlPlane, opts metav1.UpdateOptions) (result *v1.ServiceMeshControlPlane, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(servicemeshcontrolplanesResource, c.ns, serviceMeshControlPlane), &v1.ServiceMeshControlPlane{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ServiceMeshControlPlane), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeServiceMeshControlPlanes) UpdateStatus(ctx context.Context, serviceMeshControlPlane *v1.ServiceMeshControlPlane, opts metav1.UpdateOptions) (*v1.ServiceMeshControlPlane, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(servicemeshcontrolplanesResource, "status", c.ns, serviceMeshControlPlane), &v1.ServiceMeshControlPlane{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ServiceMeshControlPlane), err
}

// Delete takes name of the serviceMeshControlPlane and deletes it. Returns an error if one occurs.
func (c *FakeServiceMeshControlPlanes) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(servicemeshcontrolplanesResource, c.ns, name, opts), &v1.ServiceMeshControlPlane{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServiceMeshControlPlanes) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(servicemeshcontrolplanesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ServiceMeshControlPlaneList{})
	return err
}

// Patch applies the patch and returns the patched serviceMeshControlPlane.
func (c *FakeServiceMeshControlPlanes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ServiceMeshControlPlane, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(servicemeshcontrolplanesResource, c.ns, name, pt, data, subresources...), &v1.ServiceMeshControlPlane{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ServiceMeshControlPlane), err
}
