// Copyright Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1 "maistra.io/api/federation/v1"
)

// FakeExportedServiceSets implements ExportedServiceSetInterface
type FakeExportedServiceSets struct {
	Fake *FakeFederationV1
	ns   string
}

var exportedservicesetsResource = v1.SchemeGroupVersion.WithResource("exportedservicesets")

var exportedservicesetsKind = v1.SchemeGroupVersion.WithKind("ExportedServiceSet")

// Get takes name of the exportedServiceSet, and returns the corresponding exportedServiceSet object, and an error if there is any.
func (c *FakeExportedServiceSets) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ExportedServiceSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(exportedservicesetsResource, c.ns, name), &v1.ExportedServiceSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ExportedServiceSet), err
}

// List takes label and field selectors, and returns the list of ExportedServiceSets that match those selectors.
func (c *FakeExportedServiceSets) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ExportedServiceSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(exportedservicesetsResource, exportedservicesetsKind, c.ns, opts), &v1.ExportedServiceSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ExportedServiceSetList{ListMeta: obj.(*v1.ExportedServiceSetList).ListMeta}
	for _, item := range obj.(*v1.ExportedServiceSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested exportedServiceSets.
func (c *FakeExportedServiceSets) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(exportedservicesetsResource, c.ns, opts))

}

// Create takes the representation of a exportedServiceSet and creates it.  Returns the server's representation of the exportedServiceSet, and an error, if there is any.
func (c *FakeExportedServiceSets) Create(ctx context.Context, exportedServiceSet *v1.ExportedServiceSet, opts metav1.CreateOptions) (result *v1.ExportedServiceSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(exportedservicesetsResource, c.ns, exportedServiceSet), &v1.ExportedServiceSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ExportedServiceSet), err
}

// Update takes the representation of a exportedServiceSet and updates it. Returns the server's representation of the exportedServiceSet, and an error, if there is any.
func (c *FakeExportedServiceSets) Update(ctx context.Context, exportedServiceSet *v1.ExportedServiceSet, opts metav1.UpdateOptions) (result *v1.ExportedServiceSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(exportedservicesetsResource, c.ns, exportedServiceSet), &v1.ExportedServiceSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ExportedServiceSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeExportedServiceSets) UpdateStatus(ctx context.Context, exportedServiceSet *v1.ExportedServiceSet, opts metav1.UpdateOptions) (*v1.ExportedServiceSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(exportedservicesetsResource, "status", c.ns, exportedServiceSet), &v1.ExportedServiceSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ExportedServiceSet), err
}

// Delete takes name of the exportedServiceSet and deletes it. Returns an error if one occurs.
func (c *FakeExportedServiceSets) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(exportedservicesetsResource, c.ns, name, opts), &v1.ExportedServiceSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExportedServiceSets) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(exportedservicesetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ExportedServiceSetList{})
	return err
}

// Patch applies the patch and returns the patched exportedServiceSet.
func (c *FakeExportedServiceSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ExportedServiceSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(exportedservicesetsResource, c.ns, name, pt, data, subresources...), &v1.ExportedServiceSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ExportedServiceSet), err
}
